# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '9.0'

target 'DentalAssessment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for DentalAssessment
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Eureka', '~> 5.0.0'
  pod 'SuggestionRow'
  pod 'CodableFirebase'
end
